defaults: &defaults
  encoding: utf-8
  username: laurenceberry
  password:
  pool: 5
  host: 127.0.0.1
  reconnect: true
  adapter: postgresql

development:
  <<: *defaults
  database: value_dev

test: &test
  <<: *defaults
  database: value_test
